employee_management/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('employees/', employees_list, name='employees_list'), 
    path('add_employee/', add_employee, name='add_employee'),
     path('delete_employee/<int:employee_id>/', delete_employee, name='delete_employee'),
    path('department_hierarchy/', department_hierarchy, name='department_hierarchy'),
    path('departments/', departments_list, name='departments_list'),
    path('add_department/', add_department, name='add_department'),
    path('update_department/<int:department_id>/', update_department, name='update_department'),
    path('delete_department/<int:department_id>/', delete_department, name='delete_department'),
    path('update_employee/<int:employee_id>/', update_employee, name='update_employee'),
    path('department_salary_costs/', department_salary_costs, name='department_salary_costs'),
    path('add_salary/', add_salary, name='add_salary'),
    path('update_salary/<int:salary_id>/', update_salary, name='update_salary'),
    path('salaries/', salaries_list, name='salaries_list'),
]

employee_management_system/urls.py
from django.contrib import admin
from django.urls import include, path
from employee_management import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index),
    path('employee/', include('employee_management.urls')),
    
]

employee_management/models.py
from django.db import models

class Department(models.Model):
    name = models.CharField(max_length=100)
    floor = models.IntegerField()

class Employee(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.TextField()
    designation = models.CharField(max_length=20, choices=[('Associate', 'Associate'), ('TL', 'TL'), ('Manager', 'Manager')])
    reporting_manager = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)


class EmployeeSalary(models.Model):
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)
    salary_amount = models.DecimalField(max_digits=10, decimal_places=2)
    start_date = models.DateField()
    end_date = models.DateField()

employee_management/forms.py
from django import forms
from .models import Department, Employee, EmployeeSalary

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name', 'floor']

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name', 'email', 'address', 'designation', 'reporting_manager', 'department']


class EmployeeSalaryForm(forms.ModelForm):
    class Meta:
        model = EmployeeSalary
        fields = ['employee', 'salary_amount', 'start_date', 'end_date']

employee_management/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.db import models
from .models import Department, Employee, EmployeeSalary
from .forms import *
from django.db.models import Sum
from django.utils.timezone import make_aware
from datetime import datetime




def index(request):
    return render(request, "index.html")


def add_employee(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("employees_list")
    else:
        form = EmployeeForm()

    managers = Employee.objects.filter(designation__in=["TL", "Manager"])

    return render(
        request,
        "add_employee.html",
        {"form": form, "departments": Department.objects.all(), "managers": managers},
    )


def delete_employee(request, employee_id):
    employee = get_object_or_404(Employee, id=employee_id)
    employee.delete()
    return redirect("employees_list")


def department_hierarchy(request):
    departments = Department.objects.all()
    return render(request, "department_hierarchy.html", {"departments": departments})


def department_salary_costs(request):
    if request.method == "POST":
        start_date = request.POST.get("start_date")
        end_date = request.POST.get("end_date")

        salary_costs = (
            EmployeeSalary.objects.filter(
                start_date__lte=end_date, end_date__gte=start_date
            )
            .values("employee__department__name")
            .annotate(total_salary=models.Sum("salary"))
        )
        return render(
            request, "department_salary_costs.html", {"salary_costs": salary_costs}
        )
    return render(request, "department_salary_costs.html")


def departments_list(request):
    departments = Department.objects.all()
    return render(request, "departments_list.html", {"departments": departments})


def add_department(request):
    if request.method == "POST":
        form = DepartmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("departments_list")
    else:
        form = DepartmentForm()
    return render(request, "add_department.html", {"form": form})


def update_department(request, department_id):
    department = get_object_or_404(Department, id=department_id)
    if request.method == "POST":
        form = DepartmentForm(request.POST, instance=department)
        if form.is_valid():
            form.save()
            return redirect("departments_list")
    else:
        form = DepartmentForm(instance=department)
    return render(
        request, "update_department.html", {"form": form, "department": department}
    )


def delete_department(request, department_id):
    department = get_object_or_404(Department, id=department_id)
    department.delete()
    return redirect("departments_list")


def employees_list(request):
    employees = Employee.objects.all()
    return render(request, "employees_list.html", {"employees": employees})


def update_employee(request, employee_id):
    employee = get_object_or_404(Employee, id=employee_id)
    if request.method == "POST":
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return redirect("employees_list")
    else:
        form = EmployeeForm(instance=employee)
    return render(
        request,
        "update_employee.html",
        {"form": form, "employee": employee, "departments": Department.objects.all()},
    )


def add_salary(request):
    if request.method == "POST":
        form = EmployeeSalaryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("salaries_list")
    else:
        form = EmployeeSalaryForm()

    return render(
        request, "add_salary.html", {"form": form, "employees": Employee.objects.all()}
    )
    
def update_salary(request, salary_id):
    salary = EmployeeSalary.objects.get(id=salary_id)

    if request.method == 'POST':
        form = EmployeeSalaryForm(request.POST, instance=salary)
        if form.is_valid():
            form.save()
            return redirect('salaries_list')
    else:
        form = EmployeeSalaryForm(instance=salary)

    return render(request, 'update_salary.html', {'form': form, 'salary': salary})



def salaries_list(request):
    employee_salaries = EmployeeSalary.objects.all()
    employee_wise_salaries = {}
    for salary in employee_salaries:
        if salary.employee.name not in employee_wise_salaries:
            employee_wise_salaries[salary.employee.name] = []

        employee_wise_salaries[salary.employee.name].append(
            {
                "salary_amount": salary.salary_amount,
                "start_date": salary.start_date,
                "end_date": salary.end_date,
                "salary_id" : salary.id
            }
        )
    return render(
        request,
        "salaries_list.html",
        {"employee_wise_salaries": employee_wise_salaries},
    )

def department_salary_costs(request):
    if request.method == 'GET':
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')

        if start_date and end_date:
            # Group by department and calculate total salary for each department
            queryset = EmployeeSalary.objects.filter(
                start_date__range=[start_date, end_date],
                end_date__range=[start_date, end_date]
            ).values('employee__department__name').annotate(total_salary=Sum('salary_amount'))

            context = {
                'queryset': queryset,
                'start_date': start_date,
                'end_date': end_date,
            }
            return render(request, 'department_salary_costs.html', context)

    return render(request, 'department_salary_costs.html')

employee_management/templates/add_department.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Department</title>
</head>
<body>
    <nav style="display: flex; gap: 20px; font-weight:800; font-size:larger">
        <a href="{% url 'employees_list' %}" style="text-decoration: none;">Employees</a>
        <a href="{% url 'add_employee' %}" style="text-decoration: none;">Add Employee</a>
        <a href="{% url 'update_employee' employee_id=5 %}" style="text-decoration: none;">Update Employee</a>
        <a href="{% url 'departments_list' %}" style="text-decoration: none;">Departments</a>
        <a href="{% url 'department_hierarchy' %}" style="text-decoration: none;">Department Hierarchy</a>
        <a href="{% url 'add_department' %}" style="text-decoration: none;">Add Department</a>
        <a href="{% url 'update_department' department_id=2 %}" style="text-decoration: none;">Update Department</a>
        <a href="{% url 'salaries_list' %}" style="text-decoration: none;">Salaries List</a>
        <a href="{% url 'add_salary' %}" style="text-decoration: none;">Add Salary</a>
        <a href="{% url 'update_salary' salary_id=8 %}" style="text-decoration: none;">Update Salary</a>
        <a href="{% url 'department_salary_costs' %}" style="text-decoration: none;">Department Wise Salary
            Costs</a>
    </nav>
    <hr>
<h2 style="text-align: center;">Add Department</h2>
<div class="mjj" style="display: flex; justify-content:center">

    <form method="post" action="{% url 'add_department' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Department">
    </form>
    
</div>
</body>
</html>

employee_management/templates/add_employee.html
<!DOCTYPE html>
<html>

<head>
    <title>Add Employee</title>
    
</head>

<body>

    <nav style="display: flex; gap: 20px; font-weight:800; font-size:larger">
        <a href="{% url 'employees_list' %}" style="text-decoration: none;">Employees</a>
        <a href="{% url 'add_employee' %}" style="text-decoration: none;">Add Employee</a>
        <a href="{% url 'update_employee' employee_id=5 %}" style="text-decoration: none;">Update Employee</a>
        <a href="{% url 'departments_list' %}" style="text-decoration: none;">Departments</a>
        <a href="{% url 'department_hierarchy' %}" style="text-decoration: none;">Department Hierarchy</a>
        <a href="{% url 'add_department' %}" style="text-decoration: none;">Add Department</a>
        <a href="{% url 'update_department' department_id=2 %}" style="text-decoration: none;">Update Department</a>
        <a href="{% url 'salaries_list' %}" style="text-decoration: none;">Salaries List</a>
        <a href="{% url 'add_salary' %}" style="text-decoration: none;">Add Salary</a>
        <a href="{% url 'update_salary' salary_id=8 %}" style="text-decoration: none;">Update Salary</a>
        <a href="{% url 'department_salary_costs' %}" style="text-decoration: none;">Department Wise Salary
            Costs</a>
    </nav>
    <hr>

    <h2>Add Employee</h2>
<div class="mj" style="display: flex; justify-content:center">
    
    <form method="post" action="{% url 'add_employee' %}" >
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" name="name" required><br>

        <label for="email">Email:</label>
        <input type="email" name="email" required><br>
        
        <label for="address">Address:</label>
        <textarea name="address" required></textarea><br>
        
        <label for="designation">Designation:</label>
        <select name="designation" required>
            <option value="Associate">Associate</option>
            <option value="TL">TL</option>
            <option value="Manager">Manager</option>
        </select><br>
        
        <label for="department">Department:</label>
        <select name="department" required onchange="filterManagers(this.value)">
            {% for department in departments %}
            <option value="{{ department.id }}">{{ department.name }}</option>
            {% endfor %}
        </select><br>
        
        <label for="reporting_manager">Reporting Manager:</label>
        <select name="reporting_manager">
            <option value="" selected>None</option>
            {% for manager in managers %}
            <option value="{{ manager.id }}" data-department="{{ manager.department.id }}">{{ manager.name }}</option>
            {% endfor %}
        </select><br>

        <script>
            function filterManagers(selectedDepartment) {
                var reportingManagerDropdown = document.getElementsByName("reporting_manager")[0];
                var managerOptions = reportingManagerDropdown.getElementsByTagName("option");
                
             
                for (var i = 0; i < managerOptions.length; i++) {
                    managerOptions[i].style.display = "block";
                }
                
                for (var i = 0; i < managerOptions.length; i++) {
                    var managerDepartment = managerOptions[i].getAttribute("data-department");
                    if (managerDepartment !== selectedDepartment && selectedDepartment !== "") {
                        managerOptions[i].style.display = "none";
                    }
                }
            }
        </script>
        
        <input type="submit" value="Add Employee">
    </div>
    </form>
    
</body>

</html>

employee_management/templates/add_salary.html
<!DOCTYPE html>
<html>

<head>
    <title>Add Salary</title>
</head>

<body>
    <nav style="display: flex; gap: 20px; font-weight:800; font-size:larger">
        <a href="{% url 'employees_list' %}" style="text-decoration: none;">Employees</a>
        <a href="{% url 'add_employee' %}" style="text-decoration: none;">Add Employee</a>
        <a href="{% url 'update_employee' employee_id=5 %}" style="text-decoration: none;">Update Employee</a>
        <a href="{% url 'departments_list' %}" style="text-decoration: none;">Departments</a>
        <a href="{% url 'department_hierarchy' %}" style="text-decoration: none;">Department Hierarchy</a>
        <a href="{% url 'add_department' %}" style="text-decoration: none;">Add Department</a>
        <a href="{% url 'update_department' department_id=2 %}" style="text-decoration: none;">Update Department</a>
        <a href="{% url 'salaries_list' %}" style="text-decoration: none;">Salaries List</a>
        <a href="{% url 'add_salary' %}" style="text-decoration: none;">Add Salary</a>
        <a href="{% url 'update_salary' salary_id=8 %}" style="text-decoration: none;">Update Salary</a>
        <a href="{% url 'department_salary_costs' %}" style="text-decoration: none;">Department Wise Salary
            Costs</a>
    </nav>
    <hr>
    <h1 style="text-align: center;">Add Salary</h1>

   <div class="mjj" style="display: flex; justify-content:center">
    <form method="post" action="{% url 'add_salary' %}" >
        {% csrf_token %}

        <label for="employee" >Employee:</label>
        <select name="employee" required>
            {% for employee in employees %}
                <option value="{{ employee.id }}">{{ employee.name }}</option>
            {% endfor %}
        </select><br>

        <label for="salary_amount">Salary Amount:</label>
        <input type="text" name="salary_amount" required><br>

        <label for="start_date">Start Date:</label>
        <input type="date" name="start_date" required><br>

        <label for="end_date">End Date:</label>
        <input type="date" name="end_date" required><br>

        <input type="submit" value="Add Salary">
    </form>

   </div>
</body>

</html>

employee_management/templates/department_hierarchy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Department Hierarchy</title>
    <style>
        

        h1, h2 {
            text-align: center;
            color: black;
        }

        .org-chart {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-wrap: wrap;
        }

        .box {
            text-align: center;
            border: 1px solid #ccc;
            padding: 15px;
            margin: 10px;
            width: 180px;
            background-color: #fff;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        }

        .box h3 {
            margin: 0 0 5px;
            font-size: 1.2em;
            color: #333;
        }

        .box p {
            margin: 5px 0;
            font-size: 0.9em;
            color: #666;
        }

        .sub-box {
            margin-top: 10px;
            border: 1px solid #ddd;
            padding: 10px;
            background-color: #f9f9f9;
        }
    </style>
</head>
<body>
    <nav style="display: flex; gap: 20px; font-weight:800; font-size:larger">
        <a href="{% url 'employees_list' %}" style="text-decoration: none;">Employees</a>
        <a href="{% url 'add_employee' %}" style="text-decoration: none;">Add Employee</a>
        <a href="{% url 'update_employee' employee_id=5 %}" style="text-decoration: none;">Update Employee</a>
        <a href="{% url 'departments_list' %}" style="text-decoration: none;">Departments</a>
        <a href="{% url 'department_hierarchy' %}" style="text-decoration: none;">Department Hierarchy</a>
        <a href="{% url 'add_department' %}" style="text-decoration: none;">Add Department</a>
        <a href="{% url 'update_department' department_id=2 %}" style="text-decoration: none;">Update Department</a>
        <a href="{% url 'salaries_list' %}" style="text-decoration: none;">Salaries List</a>
        <a href="{% url 'add_salary' %}" style="text-decoration: none;">Add Salary</a>
        <a href="{% url 'update_salary' salary_id=8 %}" style="text-decoration: none;">Update Salary</a>
        <a href="{% url 'department_salary_costs' %}" style="text-decoration: none;">Department Wise Salary
            Costs</a>
    </nav>
    <hr>
    <h1>Department Hierarchy</h1>
    
    {% for department in departments %}
        <h2>{{ department.name }}</h2>
        
        <div class="org-chart">
            {% for employee in department.employee_set.all %}
                {% if not employee.reporting_manager %}
                    <div class="box">
                        <h3>{{ employee.name }}</h3>
                        <p>{{ employee.designation }}</p>
                        {% for sub_employee in employee.employee_set.all %}
                            {% include "sub_employee_box.html" with employee=sub_employee %}
                        {% endfor %}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    {% endfor %}
</body>
</html>

employee_management/templates/department_salary_costs.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Department Salary Costs</title>

    </head>

    <body>
        <nav style="display: flex; gap: 20px; font-weight:800; font-size:larger">
            <a href="{% url 'employees_list' %}" style="text-decoration: none;">Employees</a>
            <a href="{% url 'add_employee' %}" style="text-decoration: none;">Add Employee</a>
            <a href="{% url 'update_employee' employee_id=5 %}" style="text-decoration: none;">Update Employee</a>
            <a href="{% url 'departments_list' %}" style="text-decoration: none;">Departments</a>
            <a href="{% url 'department_hierarchy' %}" style="text-decoration: none;">Department Hierarchy</a>
            <a href="{% url 'add_department' %}" style="text-decoration: none;">Add Department</a>
            <a href="{% url 'update_department' department_id=2 %}" style="text-decoration: none;">Update Department</a>
            <a href="{% url 'salaries_list' %}" style="text-decoration: none;">Salaries List</a>
            <a href="{% url 'add_salary' %}" style="text-decoration: none;">Add Salary</a>
            <a href="{% url 'update_salary' salary_id=8 %}" style="text-decoration: none;">Update Salary</a>
            <a href="{% url 'department_salary_costs' %}" style="text-decoration: none;">Department Wise Salary
                Costs</a>
        </nav>
        <hr>
        <h1>Department Salary Costs</h1>
        <div class="container">

            <form method="GET" action="{% url 'department_salary_costs' %}">
                <label for="start_date">Start Date:</label>
                <input type="date" id="start_date" name="start_date" required>

                <label for="end_date">End Date:</label>
                <input type="date" id="end_date" name="end_date" required>

                <button type="submit">Submit</button>
            </form>


            {% if queryset %}
            <h2>Total Salaries between {{ start_date }} and {{ end_date }}</h2>
            <table border="2">
                <thead>
                    <tr>
                        <th>Department</th>
                        <th>Total Salary</th>
                    </tr>
                </thead>
                <tbody>
                    {% for department in queryset %}
                    <tr>
                        <td>{{ department.employee__department__name }}</td>
                        <td>${{ department.total_salary }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </body>

</html>

employee_management/templates/departments_list.html
<!-- departments_list.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Departments List</title>
</head>
<body>
    <nav style="display: flex; gap: 20px; font-weight:800; font-size:larger">
        <a href="{% url 'employees_list' %}" style="text-decoration: none;">Employees</a>
        <a href="{% url 'add_employee' %}" style="text-decoration: none;">Add Employee</a>
        <a href="{% url 'update_employee' employee_id=5 %}" style="text-decoration: none;">Update Employee</a>
        <a href="{% url 'departments_list' %}" style="text-decoration: none;">Departments</a>
        <a href="{% url 'department_hierarchy' %}" style="text-decoration: none;">Department Hierarchy</a>
        <a href="{% url 'add_department' %}" style="text-decoration: none;">Add Department</a>
        <a href="{% url 'update_department' department_id=2 %}" style="text-decoration: none;">Update Department</a>
        <a href="{% url 'salaries_list' %}" style="text-decoration: none;">Salaries List</a>
        <a href="{% url 'add_salary' %}" style="text-decoration: none;">Add Salary</a>
        <a href="{% url 'update_salary' salary_id=8 %}" style="text-decoration: none;">Update Salary</a>
        <a href="{% url 'department_salary_costs' %}" style="text-decoration: none;">Department Wise Salary
            Costs</a>
    </nav>
    <hr>
<h2>Departments List</h2>

<ul>
    {% for department in departments %}
        <li>{{ department.name }} - <a href="{% url 'update_department' department.id %}">Edit</a> | <a href="{% url 'delete_department' department.id %}">Delete</a></li>
    {% endfor %}
</ul>

</body>
</html>

employee_management/templates/employees_list.html
<!DOCTYPE html>
<html>

    <head>
        <title>Employees List</title>

    </head>

    <body>

        <nav style="display: flex; gap: 20px; font-weight:800; font-size:larger">
            <a href="{% url 'employees_list' %}" style="text-decoration: none;">Employees</a>
            <a href="{% url 'add_employee' %}" style="text-decoration: none;">Add Employee</a>
            <a href="{% url 'update_employee' employee_id=5 %}" style="text-decoration: none;">Update Employee</a>
            <a href="{% url 'departments_list' %}" style="text-decoration: none;">Departments</a>
            <a href="{% url 'department_hierarchy' %}" style="text-decoration: none;">Department Hierarchy</a>
            <a href="{% url 'add_department' %}" style="text-decoration: none;">Add Department</a>
            <a href="{% url 'update_department' department_id=2 %}" style="text-decoration: none;">Update Department</a>
            <a href="{% url 'salaries_list' %}" style="text-decoration: none;">Salaries List</a>
            <a href="{% url 'add_salary' %}" style="text-decoration: none;">Add Salary</a>
            <a href="{% url 'update_salary' salary_id=8 %}" style="text-decoration: none;">Update Salary</a>
            <a href="{% url 'department_salary_costs' %}" style="text-decoration: none;">Department Wise Salary
                Costs</a>
        </nav>
<hr>

        <h1 style="text-align: center;">Employees List</h1>

        <table border="1px" align="center">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Department</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td>{{ employee.name }}</td>
                    <td>{{ employee.department.name }}</td>
                    <td><a href="{% url 'update_employee' employee.id %}">Edit</a>
                        <td><a href="{% url 'delete_employee' employee.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    
        <a href="{% url 'add_employee' %}" style="text-align: center;">Add Employee</a>

    </body>

</html>

employee_management/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <nav style="display: flex; gap: 20px; font-weight:800; font-size:larger">
        <a href="{% url 'employees_list' %}" style="text-decoration: none;">Employees</a>
        <a href="{% url 'add_employee' %}" style="text-decoration: none;">Add Employee</a>
        <a href="{% url 'update_employee' employee_id=5 %}" style="text-decoration: none;">Update Employee</a>
        <a href="{% url 'departments_list' %}" style="text-decoration: none;">Departments</a>
        <a href="{% url 'department_hierarchy' %}" style="text-decoration: none;">Department Hierarchy</a>
        <a href="{% url 'add_department' %}" style="text-decoration: none;">Add Department</a>
        <a href="{% url 'update_department' department_id=2 %}" style="text-decoration: none;">Update Department</a>
        <a href="{% url 'salaries_list' %}" style="text-decoration: none;">Salaries List</a>
        <a href="{% url 'add_salary' %}" style="text-decoration: none;">Add Salary</a>
        <a href="{% url 'update_salary' salary_id=8 %}" style="text-decoration: none;">Update Salary</a>
        <a href="{% url 'department_salary_costs' %}" style="text-decoration: none;">Department Wise Salary
            Costs</a>
    </nav>
    <hr>
    <!-- <div class="container" style="text-align:center; ">
        <a href="/employee/employees" style="text-decoration:none"><h1>Employees Section</h1></a>
        <a href="/employee/departments" style="text-decoration:none"><h1>Department Section</h1></a>
        <a href="/employee/salaries" style="text-decoration:none"><h1>Salary Section</h1></a>
    </div> -->
</body>
</html>

employee_management/templates/manage_departments.html
<!DOCTYPE html>
<html>
<head>
    <title>Manage Departments</title>
</head>
<body>
    <nav style="display: flex; gap: 20px; font-weight:800; font-size:larger">
        <a href="{% url 'employees_list' %}" style="text-decoration: none;">Employees</a>
        <a href="{% url 'add_employee' %}" style="text-decoration: none;">Add Employee</a>
        <a href="{% url 'update_employee' employee_id=5 %}" style="text-decoration: none;">Update Employee</a>
        <a href="{% url 'departments_list' %}" style="text-decoration: none;">Departments</a>
        <a href="{% url 'department_hierarchy' %}" style="text-decoration: none;">Department Hierarchy</a>
        <a href="{% url 'add_department' %}" style="text-decoration: none;">Add Department</a>
        <a href="{% url 'update_department' department_id=2 %}" style="text-decoration: none;">Update Department</a>
        <a href="{% url 'salaries_list' %}" style="text-decoration: none;">Salaries List</a>
        <a href="{% url 'add_salary' %}" style="text-decoration: none;">Add Salary</a>
        <a href="{% url 'update_salary' salary_id=8 %}" style="text-decoration: none;">Update Salary</a>
        <a href="{% url 'department_salary_costs' %}" style="text-decoration: none;">Department Wise Salary
            Costs</a>
    </nav>
    <hr>
<h2>Manage Departments</h2>

<ul>
    <li><a href="{% url 'add_department' %}">Add Department</a></li>
    <li><a href="{% url 'departments_list' %}">View Departments</a></li>
</ul>

</body>
</html>

employee_management/templates/sub_employee_box.html
<div class="box">
    {{ employee.name }} ({{ employee.designation }})
    {% if employee.employee_set.all %}
        <div class="org-chart">
            {% for sub_employee in employee.employee_set.all %}
                {% include "sub_employee_box.html" with employee=sub_employee %}
            {% endfor %}
        </div>
    {% endif %}
</div>

employee_management/templates/update_department.html
<!DOCTYPE html>
<html>
<head>
    <title>Update Department</title>
</head>
<body>
    <nav style="display: flex; gap: 20px; font-weight:800; font-size:larger">
        <a href="{% url 'employees_list' %}" style="text-decoration: none;">Employees</a>
        <a href="{% url 'add_employee' %}" style="text-decoration: none;">Add Employee</a>
        <a href="{% url 'update_employee' employee_id=5 %}" style="text-decoration: none;">Update Employee</a>
        <a href="{% url 'departments_list' %}" style="text-decoration: none;">Departments</a>
        <a href="{% url 'department_hierarchy' %}" style="text-decoration: none;">Department Hierarchy</a>
        <a href="{% url 'add_department' %}" style="text-decoration: none;">Add Department</a>
        <a href="{% url 'update_department' department_id=2 %}" style="text-decoration: none;">Update Department</a>
        <a href="{% url 'salaries_list' %}" style="text-decoration: none;">Salaries List</a>
        <a href="{% url 'add_salary' %}" style="text-decoration: none;">Add Salary</a>
        <a href="{% url 'update_salary' salary_id=8 %}" style="text-decoration: none;">Update Salary</a>
        <a href="{% url 'department_salary_costs' %}" style="text-decoration: none;">Department Wise Salary
            Costs</a>
    </nav>
    <hr>
<h2>Update Department</h2>

<form method="post" action="{% url 'update_department' department.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update Department">
</form>

</body>
</html>